# Generated by Django 4.2.2 on 2023-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_views_post_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visitors',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
